version: "3.9"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - staticfiles:/srv/static:ro
      - caddy_data:/data
      - caddy_config:/config
      # Keep uploaded files on host filesystem to ease migration
      - ./upload:/srv/upload:ro,z

  web:
    build: .
    restart: unless-stopped
    volumes:
      - staticfiles:/app/static
      # Keep database and uploaded files on host filesystem to ease migration
      - ./db.sqlite3:/app/db.sqlite3:z
      - ./upload:/app/upload:z
    env_file: ${DEPLOYMENT_ENVIRONMENT}.env

volumes:
  caddy_data:
  caddy_config:
  # Collect Django staticfiles at runtime and share with Caddy
  staticfiles:
