# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0008_auto_20160414_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
    ]
