# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0009_auto_20160414_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='affiliation',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='forenames',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='research_area',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='surname',
            field=models.CharField(max_length=120),
        ),
    ]
