# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0017_auto_20160601_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fellow',
            unique_together=set([('forenames', 'surname')]),
        ),
    ]
