# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0029_auto_20160714_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='amount_authorized_for_payment',
        ),
    ]
