# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-14 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0030_auto_20160714_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='report_url',
        ),
    ]
