# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0033_auto_20160715_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='funds_from',
            field=models.CharField(choices=[('C', 'Continuing (fellowship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration fellowship)')], default='C', max_length=1),
        ),
    ]
