# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0035_auto_20160715_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='asked_for_authorization_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='received_date',
            field=models.DateField(default=datetime.date(2016, 7, 15)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='send_to_finance_date',
            field=models.DateField(null=True),
        ),
    ]
