# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0039_auto_20160720_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='research_area',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
