# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0041_auto_20160720_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
