# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0050_auto_20160720_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='required_blog_posts',
            field=models.IntegerField(default=1),
        ),
    ]
