# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0051_event_required_blog_posts'),
        ('lowfat', '0051_auto_20160804_1425'),
    ]

    operations = [
    ]
