# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0057_blog_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_be_advertise_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='can_be_advertise_before',
            field=models.BooleanField(default=False),
        ),
    ]
