# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0059_event_extra_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='grant_used',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3')], default='SS2', max_length=4),
        ),
    ]
