# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0060_expense_grant_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recipient',
            field=models.TextField(blank=True, help_text='Keep empty if the recipient is the fellow.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='final',
            field=models.BooleanField(default=False, help_text='This is your last blog post about the event'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='final',
            field=models.BooleanField(default=False, help_text='This is your last expense claim for the event'),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='phone',
            field=models.CharField(help_text='The number that we can contact you.', max_length=120),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='research_area',
            field=models.TextField(help_text='Please describe your research'),
        ),
    ]
