# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0064_auto_20160809_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='budget_approved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='budget_request_attendance_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='budget_request_catering',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='budget_request_others',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='budget_request_subsistence_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='budget_request_travel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='budget_request_venue_hire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
