# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lowfat', '0069_auto_20160812_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowfat.Fund')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lowfat.Claimed')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
