# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0070_sentmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
