# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fat', '0071_auto_20160812_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSentMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sentmail',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='sentmail',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='sentmail',
            name='sender',
        ),
        migrations.CreateModel(
            name='BlogSentMail',
            fields=[
                ('generalsentmail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fat.GeneralSentMail')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fat.Blog')),
            ],
            bases=('fat.generalsentmail',),
        ),
        migrations.CreateModel(
            name='ExpenseSentMail',
            fields=[
                ('generalsentmail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fat.GeneralSentMail')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fat.Expense')),
            ],
            bases=('fat.generalsentmail',),
        ),
        migrations.CreateModel(
            name='FundSentMail',
            fields=[
                ('generalsentmail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fat.GeneralSentMail')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fat.Fund')),
            ],
            bases=('fat.generalsentmail',),
        ),
        migrations.DeleteModel(
            name='SentMail',
        ),
        migrations.AddField(
            model_name='generalsentmail',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fat.Claimed'),
        ),
        migrations.AddField(
            model_name='generalsentmail',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
