# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0077_expense_justification_for_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
