# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0078_auto_20160819_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='can_be_advertise_after',
            field=models.BooleanField(default=True),
        ),
    ]
