# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0080_auto_20160831_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimed',
            name='data_carpentry_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimed',
            name='software_carpentry_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
