# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0082_auto_20161215_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Claimed',
            new_name='Claimant',
        ),
        migrations.RenameField(
            model_name='claimant',
            old_name='claimedship_grant',
            new_name='claimantship_grant',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='claimed',
            new_name='claimant',
        ),
        migrations.AlterField(
            model_name='expense',
            name='funds_from',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='C', max_length=1),
        ),
    ]
