# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0085_auto_20170125_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='url',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
