# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0088_auto_20170301_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_reference',
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='invoice_reference',
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
    ]
