# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0090_auto_20170307_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
