# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0092_auto_20170308_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='funds_from_default',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='funds_from_default',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='grant_used',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3')], default='SSI2', max_length=4),
        ),
        migrations.AlterField(
            model_name='fund',
            name='grant_default',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3')], default='SSI2', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='grant_used',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3')], default='SSI2', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='grant_default',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3')], default='SSI2', max_length=4),
        ),
    ]
