# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0093_auto_20170310_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='funds_from',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='funds_from_default',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='funds_from',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='funds_from_default',
            field=models.CharField(choices=[('C', 'Continuing (claimantship)'), ('I', 'Core (Software Sustainability Institute)'), ('F', 'Grant (inauguration claimantship)')], default='F', max_length=1),
        ),
    ]
