# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0094_auto_20170314_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-added']},
        ),
        migrations.AlterModelOptions(
            name='claimant',
            options={'ordering': ['-selected', '-application_year', 'forenames', 'surname']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-received_date', 'relative_number']},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['-start_date', '-end_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='generalsentmail',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='invoice_reference',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
