# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0095_auto_20170316_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='justification_for_extra',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='justification_for_extra',
            field=models.TextField(blank=True),
        ),
    ]
