# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lowfat.validator


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0096_auto_20170316_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='draft_url',
            field=models.CharField(max_length=120, validators=[lowfat.validator.online_document]),
        ),
        migrations.AlterField(
            model_name='generalsentmail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='draft_url',
            field=models.CharField(max_length=120, validators=[lowfat.validator.online_document]),
        ),
    ]
