# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0097_auto_20170405_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('R', 'Reproved'), ('F', 'Archived'), ('C', 'Cancelled')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('R', 'Reproved'), ('F', 'Archived'), ('C', 'Cancelled')], default='U', max_length=1),
        ),
    ]
