# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0098_auto_20170420_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coauthor',
            field=models.ManyToManyField(blank=True, related_name='author', to='lowfat.Claimant'),
        ),
    ]
