# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0100_auto_20170426_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('U', 'Waiting for triage'), ('R', 'Waiting to be reviewed'), ('G', 'Waiting to be proofread'), ('L', 'Waiting to be published'), ('P', 'Published'), ('D', 'Declined'), ('O', 'Out of date')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='status',
            field=models.CharField(choices=[('U', 'Waiting for triage'), ('R', 'Waiting to be reviewed'), ('G', 'Waiting to be proofread'), ('L', 'Waiting to be published'), ('P', 'Published'), ('D', 'Declined'), ('O', 'Out of date')], default='U', max_length=1),
        ),
    ]
