# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0103_auto_20170522_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalblog',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
