# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0104_auto_20170607_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalblog',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalgeneralsentmail',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
