# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0105_auto_20170615_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('U', 'Waiting for triage'), ('R', 'Waiting to be reviewed'), ('G', 'Waiting to be proofread'), ('L', 'Waiting to be published'), ('P', 'Published'), ('D', 'Declined'), ('O', 'Out of date'), ('X', 'Remove')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('W', 'Not submitted yet'), ('S', 'Submitted (awaiting processing)'), ('C', 'Administrator checking'), ('P', 'Authoriser checking'), ('A', 'Approved (submitted to finance)'), ('F', 'Finished'), ('X', 'Remove')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('R', 'Reproved'), ('F', 'Archived'), ('C', 'Cancelled'), ('X', 'Remove')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='status',
            field=models.CharField(choices=[('U', 'Waiting for triage'), ('R', 'Waiting to be reviewed'), ('G', 'Waiting to be proofread'), ('L', 'Waiting to be published'), ('P', 'Published'), ('D', 'Declined'), ('O', 'Out of date'), ('X', 'Remove')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='status',
            field=models.CharField(choices=[('W', 'Not submitted yet'), ('S', 'Submitted (awaiting processing)'), ('C', 'Administrator checking'), ('P', 'Authoriser checking'), ('A', 'Approved (submitted to finance)'), ('F', 'Finished'), ('X', 'Remove')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('R', 'Reproved'), ('F', 'Archived'), ('C', 'Cancelled'), ('X', 'Remove')], default='U', max_length=1),
        ),
    ]
