# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import lowfat.validator


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0105_auto_20170615_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='advance_book_confirmation',
            field=models.FileField(blank=True, null=True, upload_to='expenses/', validators=[lowfat.validator.pdf]),
        ),
        migrations.AddField(
            model_name='expense',
            name='advance_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='advance_book_confirmation',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[lowfat.validator.pdf]),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='advance_booking',
            field=models.BooleanField(default=False),
        ),
    ]
