# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0108_auto_20170830_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='career_stage_when_apply',
            field=models.CharField(choices=[('E', 'Early Carrer'), ('M', 'Mid-Carrer'), ('L', 'Late Carrer')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='career_stage_when_apply',
            field=models.CharField(choices=[('E', 'Early Carrer'), ('M', 'Mid-Carrer'), ('L', 'Late Carrer')], default='M', max_length=1),
        ),
    ]
