# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import lowfat.validator


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0110_auto_20171003_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='draft_url',
            field=models.CharField(max_length=360, validators=[lowfat.validator.online_document]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_url',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tweet_url',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='website',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='website_feed',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='fund',
            name='url',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='draft_url',
            field=models.CharField(max_length=360, validators=[lowfat.validator.online_document]),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='published_url',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='tweet_url',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='website',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='website_feed',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='url',
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
