# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0111_auto_20171031_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='research_software_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='research_software_engineer',
            field=models.BooleanField(default=False),
        ),
    ]
