# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0112_auto_20171031_1133'),
        ('lowfat', '0111_auto_20171009_0933'),
    ]

    operations = [
    ]
