# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models

def fix_career_stages(apps, schema_editor):  # pylint: disable=unused-argument
    Claimant = apps.get_model("lowfat", "Claimant")  # pylint: disable=invalid-name
    for claimant in Claimant.objects.all():
        if claimant.career_stage_when_apply == "E":
            claimant.career_stage_when_apply = "2"
        elif claimant.career_stage_when_apply == "M":
            claimant.career_stage_when_apply = "3"
        elif claimant.career_stage_when_apply == "L":
            claimant.career_stage_when_apply = "4"
        claimant.save()

def reverse_fix_career_stages(apps, schema_editor):  # pylint: disable=unused-argument
    Claimant = apps.get_model("lowfat", "Claimant")  # pylint: disable=invalid-name
    for claimant in Claimant.objects.all():
        if claimant.career_stage_when_apply == "2":
            claimant.career_stage_when_apply = "E"
        elif claimant.career_stage_when_apply == "3":
            claimant.career_stage_when_apply = "M"
        elif claimant.career_stage_when_apply == "4":
            claimant.career_stage_when_apply = "L"
        claimant.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0113_merge_20171103_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimant',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='claimant',
            name='example_of_writing_url',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='claimant',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='claimant',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='claimant',
            name='institutional_website',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='claimant',
            name='interests',
            field=models.TextField(blank=True, help_text='25-50 word summary of your professional interests.'),
        ),
        migrations.AddField(
            model_name='claimant',
            name='is_into_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimant',
            name='job_title_when_apply',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='claimant',
            name='linkedin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='claimant',
            name='received_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimant',
            name='screencast_url',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='example_of_writing_url',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='group',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='institutional_website',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='interests',
            field=models.TextField(blank=True, help_text='25-50 word summary of your professional interests.'),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='is_into_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='job_title_when_apply',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='linkedin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='received_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='screencast_url',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='career_stage_when_apply',
            field=models.CharField(choices=[('1', 'Phase 1 - Junior (e.g. PhD candidate, Junior Research Software Engineer)'), ('2', 'Early (e.g Research Assistant\\/Associate, first grant holder, Lecturer, Research Software Engineer)'), ('3', 'Mid \\/ Recognised (e.g. Senior Lecturer, Reader, Senior Researcher, Senior Research Software Engineer, Research Software Group Leader)'), ('4', 'Established \\/ Experienced \\/ Senior  (e.g. Professor, Director of Research Computing, Distinguished Engineer, Chief Data Scientist)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='photo',
            field=models.FileField(blank=True, help_text='A professionally oriented (i.e. work related) main picture of yourself that you are happy to be published on the web - this should be 300px wide and 400px high (exact please).', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='work_description',
            field=models.TextField(blank=True, help_text='200-300 words describing the work you do, this can include your plans for Fellowship.'),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='career_stage_when_apply',
            field=models.CharField(choices=[('1', 'Phase 1 - Junior (e.g. PhD candidate, Junior Research Software Engineer)'), ('2', 'Early (e.g Research Assistant\\/Associate, first grant holder, Lecturer, Research Software Engineer)'), ('3', 'Mid \\/ Recognised (e.g. Senior Lecturer, Reader, Senior Researcher, Senior Research Software Engineer, Research Software Group Leader)'), ('4', 'Established \\/ Experienced \\/ Senior  (e.g. Professor, Director of Research Computing, Distinguished Engineer, Chief Data Scientist)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='photo',
            field=models.TextField(blank=True, help_text='A professionally oriented (i.e. work related) main picture of yourself that you are happy to be published on the web - this should be 300px wide and 400px high (exact please).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='work_description',
            field=models.TextField(blank=True, help_text='200-300 words describing the work you do, this can include your plans for Fellowship.'),
        ),
        migrations.RunPython(
            fix_career_stages,
            reverse_fix_career_stages
        ),
    ]
