# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0114_auto_20171115_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='career_stage_when_apply',
            field=models.CharField(choices=[('1', 'Phase 1 - Junior (e.g. PhD candidate, Junior Research Software Engineer)'), ('2', 'Early (e.g Research Assistant/Associate, first grant holder, Lecturer, Research Software Engineer)'), ('3', 'Mid / Recognised (e.g. Senior Lecturer, Reader, Senior Researcher, Senior Research Software Engineer, Research Software Group Leader)'), ('4', 'Established / Experienced / Senior  (e.g. Professor, Director of Research Computing, Distinguished Engineer, Chief Data Scientist)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='career_stage_when_apply',
            field=models.CharField(choices=[('1', 'Phase 1 - Junior (e.g. PhD candidate, Junior Research Software Engineer)'), ('2', 'Early (e.g Research Assistant/Associate, first grant holder, Lecturer, Research Software Engineer)'), ('3', 'Mid / Recognised (e.g. Senior Lecturer, Reader, Senior Researcher, Senior Research Software Engineer, Research Software Group Leader)'), ('4', 'Established / Experienced / Senior  (e.g. Professor, Director of Research Computing, Distinguished Engineer, Chief Data Scientist)')], default='M', max_length=1),
        ),
    ]
