# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0115_auto_20171115_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimant',
            options={'ordering': ['-fellow', '-application_year', 'forenames', 'surname']},
        ),
        migrations.RenameField(
            model_name='claimant',
            old_name='activated',
            new_name='collaborator',
        ),
        migrations.RenameField(
            model_name='claimant',
            old_name='selected',
            new_name='fellow',
        ),
        migrations.RenameField(
            model_name='historicalclaimant',
            old_name='activated',
            new_name='collaborator',
        ),
        migrations.RenameField(
            model_name='historicalclaimant',
            old_name='selected',
            new_name='fellow',
        ),
    ]
