# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0115_auto_20171115_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='photo_work_description',
            field=models.FileField(blank=True, help_text='A professionally oriented (i.e. work related) main picture of yourself that you are happy to be published on the web - this should be 300px wide and 400px high (exact please).', null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='photo_work_description',
            field=models.TextField(blank=True, help_text='A professionally oriented (i.e. work related) main picture of yourself that you are happy to be published on the web - this should be 300px wide and 400px high (exact please).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='photo',
            field=models.FileField(blank=True, help_text='A professionally oriented (i.e. work related) thumbnail picture of yourself that you are happy to be published on the web - this should be 150px wide and 150px high (exact please).', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='photo',
            field=models.TextField(blank=True, help_text='A professionally oriented (i.e. work related) thumbnail picture of yourself that you are happy to be published on the web - this should be 150px wide and 150px high (exact please).', max_length=100, null=True),
        ),
    ]
