# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0116_auto_20171117_1519'),
        ('lowfat', '0116_auto_20171120_1346'),
    ]

    operations = [
    ]
