# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0117_merge_20171120_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='bitbucket',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='bitbucket',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
