# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0120_auto_20180206_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='attended_inaugural_meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='attended_inaugural_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
