# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0124_auto_20180223_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-added', 'relative_number']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='received_date',
        ),
    ]
