# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0125_auto_20180223_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['-start_date', '-end_date', 'title']},
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='historicalfund',
            old_name='name',
            new_name='title',
        ),
    ]
