# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0126_auto_20180412_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='category_other',
        ),
        migrations.RemoveField(
            model_name='historicalfund',
            name='category_other',
        ),
        migrations.AddField(
            model_name='fund',
            name='focus',
            field=models.CharField(choices=[('D', 'Domain specific'), ('C', 'Cross cutting')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='focus',
            field=models.CharField(choices=[('D', 'Domain specific'), ('C', 'Cross cutting')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('A', 'Attending'), ('H', 'Organising')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='category',
            field=models.CharField(choices=[('A', 'Attending'), ('H', 'Organising')], default='A', max_length=1),
        ),
    ]
