# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0127_auto_20180412_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='grant_used',
            new_name='grant',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='funds_from',
            new_name='grant_heading',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='grant_default',
            new_name='grant',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_from_default',
            new_name='grant_heading',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='grant_used',
            new_name='grant',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='funds_from',
            new_name='grant_heading',
        ),
        migrations.RenameField(
            model_name='historicalfund',
            old_name='grant_default',
            new_name='grant',
        ),
        migrations.RenameField(
            model_name='historicalfund',
            old_name='funds_from_default',
            new_name='grant_heading',
        ),
    ]
