# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0128_auto_20180412_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='funds_from',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='grant_used',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='funds_from_default',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='grant_default',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='funds_from',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='grant_used',
        ),
        migrations.RemoveField(
            model_name='historicalfund',
            name='funds_from_default',
        ),
        migrations.RemoveField(
            model_name='historicalfund',
            name='grant_default',
        ),
    ]
