# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 11:27
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0129_auto_20180412_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='grant',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=None, default='SSI2/Fellowship', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='SSI1, SSI1/Core, SSI1/Fellowship, SSI1/Continuing, SSI2, SSI2/Core, SSI2/Fellowship, SSI2/Continuing, SSI3, SSI3/Core, SSI3/Fellowship, SSI3/Continuing', max_count=1, to='lowfat.Grant', tree=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='grant',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=None, default='SSI2/Fellowship', force_lowercase=True, help_text='Enter a comma-separated tag string', initial='SSI1, SSI1/Core, SSI1/Fellowship, SSI1/Continuing, SSI2, SSI2/Core, SSI2/Fellowship, SSI2/Continuing, SSI3, SSI3/Core, SSI3/Fellowship, SSI3/Continuing', max_count=1, to='lowfat.Grant', tree=True),
        ),
    ]
