# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0129_auto_20180413_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='activity',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=None, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='attending as ssi, conference, field trip, focus group, hack, knowledge exchange, local, meeting, new paradigm, new resource, organising submeeting, panel, paying for others, policy, poster presentation, prize, roundtable, roundtable/lead, software Special Interest Group, ssi organised, supported collaborator, survey, talk at, talk at/invited, teaching at, teaching as helper, training/attending, training/organiser, unconference, working group, workshop', space_delimiter=False, to='lowfat.FundActivity', tree=True),
        ),
        migrations.AlterField(
            model_name='fundactivity',
            name='protected',
            field=models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0'),
        ),
    ]
