# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0130_auto_20180413_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalclaimant',
            name='mentor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lowfat.Claimant'),
        ),
    ]
