# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0131_auto_20180416_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundactivity',
            options={'verbose_name': 'Fund Activity Tag', 'verbose_name_plural': 'Fund Activity Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='fundactivity',
            unique_together=set([]),
        ),
    ]
