# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0132_auto_20180416_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('W', 'Not submitted yet'), ('S', 'Submitted (awaiting processing)'), ('C', 'Administrator checking'), ('P', 'Authoriser checking'), ('A', 'Approved (submitted to finance)'), ('F', 'Finished'), ('R', 'Rejected'), ('X', 'Remove')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='status',
            field=models.CharField(choices=[('W', 'Not submitted yet'), ('S', 'Submitted (awaiting processing)'), ('C', 'Administrator checking'), ('P', 'Authoriser checking'), ('A', 'Approved (submitted to finance)'), ('F', 'Finished'), ('R', 'Rejected'), ('X', 'Remove')], default='S', max_length=1),
        ),
    ]
