# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 17:00
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0133_auto_20180418_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='activity',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view=None, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='attending as ssi, conference, field trip, focus group, hack, knowledge exchange, local, meeting, new paradigm, new resource, organising submeeting, panel, paying for others, policy, poster presentation, prize, roundtable, roundtable/lead, software Special Interest Group, ssi organised, supported collaborator, survey, talk at, talk at/invited, teaching at, teaching as helper, training/attending, training/organiser, unconference, working group, workshop', space_delimiter=False, to='lowfat.FundActivity', tree=True),
        ),
    ]
