# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0134_auto_20180418_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundactivity',
            options={'ordering': ['name'], 'verbose_name': 'Fund Activity Tag', 'verbose_name_plural': 'Fund Activity Tags'},
        ),
    ]
