# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0135_auto_20180425_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='can_be_included_in_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='can_be_included_in_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fund',
            name='can_be_advertise_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='can_be_advertise_after',
            field=models.BooleanField(default=False),
        ),
    ]
