# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0136_auto_20180504_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='can_be_advertise_after',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='can_be_advertise_after',
            field=models.BooleanField(default=True),
        ),
    ]
