# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-28 13:07
from __future__ import unicode_literals

from django.db import migrations, models

def update_expense_status(apps, schema_editor):  # pylint: disable=unused-argument
    Expense = apps.get_model("lowfat", "Expense")  # pylint: disable=invalid-name
    for expense in Expense.objects.all():
        if expense.status == "P":
            expense.status = "C"
        elif expense.status == "F":
            expense.status = "A"
        expense.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0137_auto_20180523_0959'),
    ]

    operations = [
        migrations.RunPython(update_expense_status),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('C', 'Processing'), ('A', 'Approved'), ('R', 'Rejected'), ('X', 'Remove')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('C', 'Processing'), ('A', 'Approved'), ('R', 'Rejected'), ('X', 'Remove')], default='S', max_length=1),
        ),
    ]
