# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0139_auto_20181211_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalclaimant',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
