# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0140_auto_20181212_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='access_token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='access_token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
