# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0141_auto_20181213_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='access_token_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='access_token_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
