# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0142_auto_20181221_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='access_token_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='access_token_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalblog',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalblog',
            name='access_token_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='access_token_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
