# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-23 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0143_auto_20181221_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='application_year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('M', 'Approved'), ('R', 'Rejected'), ('F', 'Archived'), ('C', 'Cancelled'), ('X', 'Remove')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='application_year',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('M', 'Approved'), ('R', 'Rejected'), ('F', 'Archived'), ('C', 'Cancelled'), ('X', 'Remove')], default='U', max_length=1),
        ),
    ]
