# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0144_auto_20190123_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='success_reported',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='success_targeted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='success_reported',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='success_targeted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
