# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0145_auto_20181213_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='success_targeted',
            field=models.TextField(help_text='Please specify what outputs (what maybe be produced) and outcomes (what change it could lead to) are likely to be produced from your participation in this event. These can include learning goals being met, collaborations, reports etc.'),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='success_targeted',
            field=models.TextField(help_text='Please specify what outputs (what maybe be produced) and outcomes (what change it could lead to) are likely to be produced from your participation in this event. These can include learning goals being met, collaborations, reports etc.'),
        ),
    ]
