# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0146_auto_20190219_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recipient_connection',
            field=models.CharField(blank=True, help_text='You need to provide a reason for submit the recipient claim. An common reasons is "because the recipient was of of the speakers on that workshop."', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='recipient_connection',
            field=models.CharField(blank=True, help_text='You need to provide a reason for submit the recipient claim. An common reasons is "because the recipient was of of the speakers on that workshop."', max_length=120),
        ),
    ]
