# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0147_auto_20190219_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='grant',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3'), ('SSI4', 'Software Sustainability Institute - Phase 4')], default='SSI3', max_length=4),
        ),
        migrations.AlterField(
            model_name='fund',
            name='grant',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3'), ('SSI4', 'Software Sustainability Institute - Phase 4')], default='SSI3', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='grant',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3'), ('SSI4', 'Software Sustainability Institute - Phase 4')], default='SSI3', max_length=4),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='grant',
            field=models.CharField(choices=[('SSI1', 'Software Sustainability Institute - Phase 1'), ('SSI2', 'Software Sustainability Institute - Phase 2'), ('SSI3', 'Software Sustainability Institute - Phase 3'), ('SSI4', 'Software Sustainability Institute - Phase 4')], default='SSI3', max_length=4),
        ),
    ]
