# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-09 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import lowfat.models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0148_auto_20190430_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='approval_chain',
            field=models.CharField(choices=[('fellows', 'FELLOWS'), ('onetime', 'ONE_TIME')], default=lowfat.models.ApprovalChain('fellows'), max_length=8),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='approval_chain',
            field=models.CharField(choices=[('fellows', 'FELLOWS'), ('onetime', 'ONE_TIME')], default=lowfat.models.ApprovalChain('fellows'), max_length=8),
        ),
        migrations.AlterField(
            model_name='fund',
            name='required_blog_posts',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='required_blog_posts',
            field=models.IntegerField(blank=True),
        ),
    ]
