# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-10 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0148_auto_20190430_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsentmail',
            name='message_id',
            field=models.CharField(default=1234, max_length=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgeneralsentmail',
            name='message_id',
            field=models.CharField(default=1234, max_length=360),
            preserve_default=False,
        ),
    ]
