# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-28 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0150_update_default_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='application_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2023, 3, 31)),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='application_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2023, 3, 31)),
        ),
    ]
