# Generated by Django 3.2.7 on 2021-11-12 11:39

import logging

from django.db import migrations
from django.utils.text import slugify

logger = logging.getLogger(__name__)


def fix_unicode_slugs(apps,
                      schema_editor,
                      app_name: str = 'lowfat',
                      model_name: str = 'claimant',
                      slug_field: str = 'slug'):
    """Convert unicode slugs to ASCII.
    
    Modern Django seems to do this by default, but slugs from old versions
    can contain non-ASCII characters which break URL patterns.
    """
    Model = apps.get_model(app_name, model_name)

    for obj in Model.objects.all():
        old_slug = getattr(obj, slug_field)
        new_slug = slugify(old_slug, allow_unicode=False)

        setattr(obj, slug_field, new_slug)
        obj.save()

        logger.info('Updated %s slug from %s to %s', model_name, old_slug,
                    new_slug)


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0151_auto_20210128_1408'),
    ]

    operations = [
        migrations.RunPython(fix_unicode_slugs, migrations.RunPython.noop)
    ]
