# Generated by Django 3.2.9 on 2022-01-28 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0152_fix_unicode_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='application_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2024, 3, 31)),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='application_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2024, 3, 31)),
        ),
    ]
