# Generated by Django 3.2.15 on 2023-01-06 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0154_split_claim_and_receipts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalblog',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical blog', 'verbose_name_plural': 'historical blogs'},
        ),
        migrations.AlterModelOptions(
            name='historicalclaimant',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical claimant', 'verbose_name_plural': 'historical claimants'},
        ),
        migrations.AlterModelOptions(
            name='historicalexpense',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical expense', 'verbose_name_plural': 'historical expenses'},
        ),
        migrations.AlterModelOptions(
            name='historicalfund',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical fund', 'verbose_name_plural': 'historical funds'},
        ),
        migrations.AlterModelOptions(
            name='historicalgeneralsentmail',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical general sent mail', 'verbose_name_plural': 'historical general sent mails'},
        ),
        migrations.AddField(
            model_name='fund',
            name='direct_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='direct_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='application_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2025, 3, 31)),
        ),
        migrations.AlterField(
            model_name='fund',
            name='success_targeted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalblog',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='application_year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2025, 3, 31)),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='success_targeted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalgeneralsentmail',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
