# Generated by Django 3.2.15 on 2023-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0155_auto_20230106_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supporting_docs',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='supporting_docs',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='recipient_connection',
            field=models.CharField(blank=True, help_text='You need to provide a reason for submitting the recipient claim. A common reason is "because the recipient was one of the speakers of that workshop."', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='recipient_connection',
            field=models.CharField(blank=True, help_text='You need to provide a reason for submitting the recipient claim. A common reason is "because the recipient was one of the speakers of that workshop."', max_length=120),
        ),
    ]
