# Generated by Django 3.2.15 on 2023-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0156_auto_20230118_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='upload_final_claim_form',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='upload_final_claim_form',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
