# Generated by Django 3.2.15 on 2023-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0158_auto_20230228_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='final',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='final',
            field=models.BooleanField(default=True),
        ),
    ]
