# Generated by Django 4.2 on 2024-07-18 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0159_auto_20230824_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimant',
            name='application_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2026, 3, 31)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('C', 'Processing'), ('A', 'Approved'), ('R', 'Rejected'), ('X', 'Removed')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('M', 'Approved by machine'), ('R', 'Rejected'), ('F', 'Archived'), ('C', 'Cancelled'), ('X', 'Removed')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='application_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='historicalclaimant',
            name='inauguration_grant_expiration',
            field=models.DateField(default=datetime.date(2026, 3, 31)),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('C', 'Processing'), ('A', 'Approved'), ('R', 'Rejected'), ('X', 'Removed')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('M', 'Approved by machine'), ('R', 'Rejected'), ('F', 'Archived'), ('C', 'Cancelled'), ('X', 'Removed')], default='U', max_length=1),
        ),
    ]
