# Generated by Django 4.2 on 2024-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lowfat', '0162_remove_fund_direct_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='claim_method',
            field=models.CharField(choices=[('A', 'A - Expense claim'), ('B', 'B - Invoice'), ('C', 'C - Combination of both')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='payment_receiver',
            field=models.CharField(choices=[('A', 'A - Me (the fellow)'), ('B', 'B - Third party'), ('C', 'C - Combination of both')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='claim_method',
            field=models.CharField(choices=[('A', 'A - Expense claim'), ('B', 'B - Invoice'), ('C', 'C - Combination of both')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='payment_receiver',
            field=models.CharField(choices=[('A', 'A - Me (the fellow)'), ('B', 'B - Third party'), ('C', 'C - Combination of both')], default='A', max_length=1),
        ),
    ]
