# Generated by Django 4.2 on 2025-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lowfat", "0163_claimant_bluesky_claimant_mastodon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimant",
            name="mastodon",
        ),
        migrations.RemoveField(
            model_name="historicalclaimant",
            name="mastodon",
        ),
        migrations.AddField(
            model_name="claimant",
            name="mastodon_instance",
            field=models.CharField(
                blank=True,
                help_text="The server or instance name (e.g. mastodon.social)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="claimant",
            name="mastodon_username",
            field=models.CharField(
                blank=True,
                help_text="Your Mastodon username (e.g. username)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="historicalclaimant",
            name="mastodon_instance",
            field=models.CharField(
                blank=True,
                help_text="The server or instance name (e.g. mastodon.social)",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="historicalclaimant",
            name="mastodon_username",
            field=models.CharField(
                blank=True,
                help_text="Your Mastodon username (e.g. username)",
                max_length=120,
            ),
        ),
    ]
