# Generated by Django 4.2 on 2025-04-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lowfat", "0164_remove_claimant_mastodon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimant",
            name="mastodon_instance",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="claimant",
            name="mastodon_username",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="historicalclaimant",
            name="mastodon_instance",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="historicalclaimant",
            name="mastodon_username",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
