# Generated by Django 4.2 on 2025-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lowfat", "0166_alter_expense_status_alter_historicalexpense_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fund",
            name="direct_invoice",
        ),
        migrations.RemoveField(
            model_name="historicalfund",
            name="direct_invoice",
        ),
        migrations.AddField(
            model_name="fund",
            name="fund_claim_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Expense claim"),
                    ("B", "B. Invoice"),
                    ("C", "C. Combination of both"),
                ],
                help_text="How will you or they be claiming?",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fund",
            name="fund_payment_receiver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Me (the Fellow)"),
                    ("B", "B. Third party"),
                    ("C", "C. Combination of both"),
                ],
                help_text="Who will receive the payment?",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfund",
            name="fund_claim_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Expense claim"),
                    ("B", "B. Invoice"),
                    ("C", "C. Combination of both"),
                ],
                help_text="How will you or they be claiming?",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfund",
            name="fund_payment_receiver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Me (the Fellow)"),
                    ("B", "B. Third party"),
                    ("C", "C. Combination of both"),
                ],
                help_text="Who will receive the payment?",
                max_length=1,
                null=True,
            ),
        ),
    ]
