# Generated by Django 4.2 on 2025-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lowfat", "0167_remove_fund_direct_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="fund_claim_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Expense claim"),
                    ("B", "B. Invoice"),
                    ("C", "C. Combination of both"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="fund_payment_receiver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Me (the Fellow)"),
                    ("B", "B. Third party"),
                    ("C", "C. Combination of both"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfund",
            name="fund_claim_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Expense claim"),
                    ("B", "B. Invoice"),
                    ("C", "C. Combination of both"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfund",
            name="fund_payment_receiver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A. Me (the Fellow)"),
                    ("B", "B. Third party"),
                    ("C", "C. Combination of both"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
