# Generated by Django 4.2 on 2025-12-18 20:09

from django.db import migrations, models


def normalise_legacy_blog_statuses(apps, schema_editor):
    Blog = apps.get_model("lowfat", "Blog")
    HistoricalBlog = apps.get_model("lowfat", "HistoricalBlog")

    # Legacy -> current mapping
    # M, O were old "cancelled-ish" states -> K (Cancelled)
    # L was old "waiting to be published" -> map to G (Waiting to be proofread)
    legacy_to_current = {
        "M": "K",
        "O": "K",
        "L": "G",
    }

    for old, new in legacy_to_current.items():
        Blog.objects.filter(status=old).update(status=new)
        HistoricalBlog.objects.filter(status=old).update(status=new)


def noop_reverse(apps, schema_editor):
    # We don't reverse this automatically (would lose information about original legacy code).
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("lowfat", "0168_alter_fund_fund_claim_method_and_more"),
    ]

    operations = [
        migrations.RunPython(normalise_legacy_blog_statuses, noop_reverse),

        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Waiting for triage"),
                    ("R", "Waiting to be reviewed"),
                    ("C", "Reviewing loop"),
                    ("G", "Waiting to be proofread"),
                    ("P", "Published"),
                    ("K", "Cancelled"),
                    ("D", "Rejected"),
                    ("X", "Removed"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Submitted"),
                    ("P", "Processing"),
                    ("E", "Returned to Claimant for Review/Action"),
                    ("N", "Pending for Approval"),
                    ("A", "Approved"),
                    ("B", "Waiting for Blog Post"),
                    ("R", "Rejected"),
                    ("C", "Cancelled"),
                    ("X", "Removed"),
                ],
                default="S",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalblog",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Waiting for triage"),
                    ("R", "Waiting to be reviewed"),
                    ("C", "Reviewing loop"),
                    ("G", "Waiting to be proofread"),
                    ("P", "Published"),
                    ("K", "Cancelled"),
                    ("D", "Rejected"),
                    ("X", "Removed"),
                ],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="historicalexpense",
            name="status",
            field=models.CharField(
                choices=[
                    ("S", "Submitted"),
                    ("P", "Processing"),
                    ("E", "Returned to Claimant for Review/Action"),
                    ("N", "Pending for Approval"),
                    ("A", "Approved"),
                    ("B", "Waiting for Blog Post"),
                    ("R", "Rejected"),
                    ("C", "Cancelled"),
                    ("X", "Removed"),
                ],
                default="S",
                max_length=1,
            ),
        ),
    ]
