# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0007_auto_20160414_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='justification',
        ),
        migrations.RemoveField(
            model_name='event',
            name='budget_request',
        ),
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='budget_request_attendance_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_request_catering',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_request_others',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_request_subsistence_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_request_travel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='budget_request_venue_hire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('A', 'Attending a conference/workshop'), ('H', 'Organising a conference/workshop (e.g. Software Carpentry)'), ('P', 'Policy related event'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
