# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0010_auto_20160414_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fellow',
            old_name='year',
            new_name='inauguration_year',
        ),
        migrations.AddField(
            model_name='fellow',
            name='facebook',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fellow',
            name='funding',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='github',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fellow',
            name='gitlab',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fellow',
            name='home_location',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='mentor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fat.Fellow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='orcid',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fellow',
            name='photo',
            field=models.FileField(default='', upload_to='photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='twitter',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fellow',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fellow',
            name='website_feed',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
