# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0014_auto_20160601_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='funding_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
