# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0015_fellow_funding_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='inauguration_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
