# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0018_auto_20160601_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
