# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0023_auto_20160617_1350'),
        ('fat', '0023_event_ad_status'),
    ]

    operations = [
    ]
