# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0024_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='fellowship_grant',
            field=models.IntegerField(default=0),
        ),
    ]
