# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0025_fellow_fellowship_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 14, 59, 43, 298429)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 7, 14, 59, 44, 986880)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 14, 59, 46, 412366)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 7, 14, 59, 47, 967906)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 14, 59, 49, 504328)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 7, 14, 59, 50, 685861)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 14, 59, 51, 820284)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 7, 14, 59, 52, 961699)),
            preserve_default=False,
        ),
    ]
