# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0032_auto_20160715_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='notes_from_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='notes_from_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes_from_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fellow',
            name='notes_from_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
