# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0036_auto_20160715_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
