# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0042_auto_20160720_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(max_length=120),
        ),
    ]
