# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0047_auto_20160720_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_url',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='draft_url',
            field=models.URLField(max_length=120),
        ),
    ]
