# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 14:47
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0052_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='fellow',
            old_name='home_location',
            new_name='home_city',
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(default='UK', max_length=2),
        ),
        migrations.AddField(
            model_name='fellow',
            name='home_country',
            field=django_countries.fields.CountryField(default='UK', max_length=2),
        ),
    ]
