# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0055_blog_tweet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
