# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0058_auto_20160808_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_sponsored',
            field=models.TextField(blank=True),
        ),
    ]
