# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0068_auto_20160812_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recipient',
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient_affiliation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient_connection',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient_fullname',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='recipient_group',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
