# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat', '0073_fund_category_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimed',
            name='slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
