# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0005_auto_20160414_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget_approve',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('U', 'Unprocessed'), ('P', 'Processing'), ('A', 'Approved'), ('R', 'Reproved')], default='U', max_length=1),
        ),
    ]
