# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 08:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fellowms', '0025_fellow_fellowship_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.CharField(max_length=120)),
                ('funding_notes', models.TextField(blank=True, null=True)),
                ('work_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forenames', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=14)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('R', 'Rather not say')], default='R', max_length=1)),
                ('home_location', models.CharField(max_length=120)),
                ('home_lon', models.FloatField(blank=True, null=True)),
                ('home_lat', models.FloatField(blank=True, null=True)),
                ('photo', models.FileField(upload_to='photos/')),
                ('research_area', models.CharField(max_length=4)),
                ('affiliation', models.CharField(max_length=120)),
                ('website', models.CharField(blank=True, max_length=120)),
                ('website_feed', models.CharField(blank=True, max_length=120)),
                ('orcid', models.CharField(blank=True, max_length=120)),
                ('github', models.CharField(blank=True, max_length=120)),
                ('gitlab', models.CharField(blank=True, max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('facebook', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='fellow',
        ),
        migrations.AlterField(
            model_name='fellow',
            name='inauguration_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fellow',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='fellowms.Collaborator'),
        ),
        migrations.AlterUniqueTogether(
            name='fellow',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='application',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to='fellowms.Collaborator'),
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='forenames',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='funding_notes',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='github',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='gitlab',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='home_lat',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='home_location',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='home_lon',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='research_area',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='website',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='website_feed',
        ),
        migrations.RemoveField(
            model_name='fellow',
            name='work_description',
        ),
        migrations.AddField(
            model_name='event',
            name='collaborator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fellowms.Collaborator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellow',
            name='application',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fellowms.Application'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together=set([('forenames', 'surname')]),
        ),
    ]
