# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fellowms', '0051_auto_20160804_1425'),
        ('fellowms', '0051_event_required_blog_posts'),
    ]

    operations = [
    ]
